server:
  port: 8089
  servlet:
    context-path: /self-motivation
spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.152.163:3306/cms?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz@WSX
mybatis:
  type-aliases-package: com.yangq.selfmotivation.dao.po
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true
search:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      index:
        number-of-replicas: 0
        number-of-shards: 3
ebean:
  dbSchema: motivation  # use this schema rather than public
  migration:
    run: true       # run database migrations on startup

datasource:
  db:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.152.163:3306/cms?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz@WSX

